# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:41
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='live/%Y/%m/%d')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
